### ISSUE TITLE
ember-cli-build merge error

### ISSUE THREAD

**Issue by samchrisinger** [toddjordan/ember-cli-dynamic-forms#29]
My team is getting:

```
Merge error: file fonts/glyphicons-halflings-regular.woff exists in /Users/sam/Documents/workspace/exp/tmp/broccoli_merge_trees-input_base_path-jlsXWLur.tmp/1 and /Users/sam/Documents/workspace/exp/tmp/broccoli_merge_trees-input_base_path-jlsXWLur.tmp/2
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
Error: Merge error: file fonts/glyphicons-halflings-regular.woff exists in /Users/sam/Documents/workspace/exp/tmp/broccoli_merge_trees-input_base_path-jlsXWLur.tmp/1 and /Users/sam/Documents/workspace/exp/tmp/broccoli_merge_trees-input_base_path-jlsXWLur.tmp/2
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
    at BroccoliMergeTrees._mergeRelativePath (/Users/sam/Documents/workspace/exp/node_modules/broccoli-merge-trees/index.js:212:17)
    at BroccoliMergeTrees._mergeRelativePath (/Users/sam/Documents/workspace/exp/node_modules/broccoli-merge-trees/index.js:238:31)
    at BroccoliMergeTrees.build (/Users/sam/Documents/workspace/exp/node_modules/broccoli-merge-trees/index.js:50:24)
    at /Users/sam/Documents/workspace/exp/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/sam/Documents/workspace/exp/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/sam/Documents/workspace/exp/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/sam/Documents/workspace/exp/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/sam/Documents/workspace/exp/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
```
after upgrading to the latest version of ember-cli-dynamic-forms. 

My guess is that this is not a bug with this library, but with another of our dependencies. 

At any rate I'm opening this ticket to document any solution we might find.

**Comment by samchrisinger** [comment]
Removing 'ember-bootstrap' as a dependency from our project fixes this. 

Looking at ember-bootstrap:'s index.js: 
https://github.com/kaliber5/ember-bootstrap/blob/master/index.js#L40

They're already doing the move that is specified here: https://github.com/toddjordan/ember-cli-dynamic-forms/commit/2ca10bb7214ddbe629cd672a94317efd279cf08f#diff-168726dbe96b3ce427e7fedce31bb0bcR11 in ember-cli-dynamic-forms

**Comment by samchrisinger** [comment]
We're not using any of the features of ember-bootstrap. Resolving this for now.

**Comment by toddjordan** [comment]
looks like ember-bootstrap can turn that move off with an option. If you did need it you could try disabling the option.
I also should import the other versions of that file similar to what they are doing...
